name: maintenance_webview_app
description: A simple Flutter WebView app that opens https://maintenance.gt.tc
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.7
  supabase_flutter: ^1.4.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.6
  image_picker: ^0.8.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^2.0.0

dependency_overrides:
  sign_in_with_apple: ^7.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
